# Generated by Django 4.2.7 on 2025-10-13 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('science', 'Science'), ('sports', 'Sports'), ('environment', 'Environment'), ('culture', 'Culture'), ('politics', 'Politics'), ('health', 'Health')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
